SPT-1990 ISG Анализ версий SPM-пакетов
surfstudio/surf-danger-spm-version-updates pull request #1
Opened 2024-03-25 08:35 UTC by Goldilocks97

# Что сделано
- Форкнут плагин
- Добавлена проверка зависимостей локальных пакетов
- Откатился на версию 0.1.0, так как текущая версия оригинального плагина не поддерживает версию ruby 2.7.6
# Как тестировать
- Создана [ветка](https://github.com/surfstudio/surf-ios-core/pull/7) для теста, в ней уже добавлены все поддерживаемые версии зависимостей для теста. Чтобы проверить свои случаи, внесите правки на этой ветки (в том числе можно попробовать настроить Dangerfile), сделайте push, дождитесь результата

2024-03-25 12:07 UTC, NullIsOne requested changes
Также вижу конфликт с main веткой в plugin.rb. Надо его разрешить.

2024-03-25 12:07 UTC, NullIsOne commented on lib/spm_version_updates/plugin.rb
> +      #remote_packages = filter_remote_packages(project)
Вижу что теперь это включено в packages
Коммент не нужен, надо удалить.

2024-03-25 12:07 UTC, NullIsOne commented on lib/spm_version_updates/local.rb
> +def package_regex(req_kind)
Я бы порекомендовал добавить тестов на новую фичу.
Создателями библиотеки тут уже подключен RSpec https://alexharv074.github.io/2016/04/23/rspec-testing-a-simple-ruby-script.html
В папке spec лежат тесты и мок-проекты (xcodeproj) с разными зависимостями.
Тело теста `spec/spm_version_updates_spec.rb`

Будет полезно сделать подобные проверки на Package.swift

2024-03-27 09:45 UTC, Goldilocks97 commented
- Добавил тесты на отслеживание локальных зависимостей
- Добавил тесты на парсинг локальных манифестов
- Отформатировал код (rubycop)

2024-03-27 10:20 UTC, Goldilocks97 commented
Изменил base, временно будем использовать ветку develop, пока не перейдем на руби 3+

2024-03-27 10:39 UTC, NullIsOne approved these changes

2024-04-15 16:42 UTC, chausovSurfStudio reviewed
честно признаюсь - тесты не осилил, надеюсь на Никиту)
поглядел вместо этого вот этот [ПР](https://github.com/surfstudio/surf-ios-core/pull/7) - есть пару вопросов. Давай порешаем - и пойдем тестить эту тему!

2024-04-15 16:42 UTC, chausovSurfStudio commented on spec/spm_version_updates_spec.rb
> +            "Newer version of (project) kean/Nuke: 12.2.0-beta.2 (but this package is set to exact version 12.1.6)\n",
я немного глупых вопросов позадаю)

чем отличается это от теста первого, где "(project) Does not report pre-release versions by default"

2024-04-16 09:32 UTC, ione-git commented on spec/spm_version_updates_spec.rb
> +            "Newer version of (project) kean/Nuke: 12.2.0-beta.2 (but this package is set to exact version 12.1.6)\n",
В первом тесте проверяется, что пререлизные версии не будут репортиться, если явно не установлен флаг
А второй тест проверяет, что при установке такого флага репортится все:)

2024-04-16 10:59 UTC, chausovSurfStudio commented on spec/spm_version_updates_spec.rb
> +            "Newer version of (project) kean/Nuke: 12.2.0-beta.2 (but this package is set to exact version 12.1.6)\n",
понял, спасибо)

2024-04-16 11:02 UTC, chausovSurfStudio approved these changes

2024-04-16 11:18 UTC, merged